(ns net.humanhelp.site.model.user.graph
  "User-specific Graph extensions.

   Ordinary User reads are entirely conventional:

   - by User ID;
   - by canonical phone;
   - by canonical email;
   - persisted field projection.

   gesso.model generates all of those from user.schema/user-descriptor.
   This namespace exists only as the stable home for genuinely derived or
   relational User Graph behavior if such behavior appears in the future.

   Do not add wrappers here around generated gesso.model resolvers or queries.")

(def custom-resolvers
  "Hand-written User Graph contribution.

   User currently has no Graph behavior beyond the conventional resolvers
   generated by gesso.model."
  [])
