(ns net.humanhelp.site.model.request.graph
  "Request-specific read composition.

   gesso.model owns ordinary persisted-document loading and generated by-ID and
   field resolvers for both Request and RequestAssignment.

   This namespace owns only Request-specific reads that require composition
   across Request-owned documents:

   - Request Assignments for one Request;
   - active Assignment lookup and uniqueness;
   - canonical Request collections for one Location;
   - Request + active-Assignment snapshots;
   - cross-document lifecycle/Assignment consistency;
   - derived Request and RequestAssignment Graph facts.

   This namespace does not load or interpret User, Membership, Invitation, or
   Organization documents. Those models remain available only through their
   public cores to Request FX."
  (:require
   [com.biffweb.graph :as graph]
   [com.biffweb.xtdb :as biff.xtdb]
   [gesso.model.core :as model]
   [gesso.model.schema :as model.schema]
   [net.humanhelp.site.model.request.domain :as request]
   [net.humanhelp.site.model.request.schema :as request.schema]))

;; =============================================================================
;; Conventional gesso.model shapes
;; =============================================================================

(def request-document-query
  (model/document-query
   request.schema/request-descriptor))

(def request-assignment-document-query
  (model/document-query
   request.schema/request-assignment-descriptor))

(def request-document-columns
  (model/document-columns
   request.schema/request-descriptor))

(def request-assignment-document-columns
  (model/document-columns
   request.schema/request-assignment-descriptor))

;; =============================================================================
;; Errors
;; =============================================================================

(defn- fail!
  [type message details]
  (throw
   (ex-info
    message
    {:error/type
     type

     :error/details
     details})))

;; =============================================================================
;; Persistence normalization
;; =============================================================================

(defn- malli-options
  [ctx]
  (or
   (:biff/malli-opts
    ctx)

   {}))

(defn- normalize-loaded-document
  [descriptor ctx document]
  (when
   document
    (model.schema/normalize-and-validate
     (:document-schema
      descriptor)

     document

     {:codec-overrides
      (get-in
       descriptor
       [:persistence
        :codec-overrides])

      :malli-options
      (malli-options
       ctx)})))

(defn- query-context!
  [ctx]
  (if
   (and
    (map? ctx)
    (or
     (:biff.xtdb/connection-pool ctx)
     (:biff.xtdb/node ctx)))
    ctx

    (fail!
     :request.graph/missing-biff-connection
     "Request reads require Biff 2 XTDB context with :biff.xtdb/connection-pool or :biff.xtdb/node."
     {:ctx-keys
      (when
       (map? ctx)
        (set
         (keys ctx)))})))

(defn- q
  [ctx query]
  (biff.xtdb/q
   (query-context! ctx)
   query))

(defn- rows
  [descriptor ctx query]
  (mapv
   #(normalize-loaded-document
     descriptor
     ctx
     %)
   (q
    ctx
    query)))

;; =============================================================================
;; Ordinary Request-owned documents
;; =============================================================================

(defn request-document
  "Returns one current Request document by UUID, or nil."
  [ctx request-id]
  (when
   (uuid?
    request-id)
    (model/load-by-id
     request.schema/request-descriptor
     ctx
     request-id)))

(defn request-assignment-document
  "Returns one current RequestAssignment document by UUID, or nil."
  [ctx assignment-id]
  (when
   (uuid?
    assignment-id)
    (model/load-by-id
     request.schema/request-assignment-descriptor
     ctx
     assignment-id)))

;; =============================================================================
;; Request Assignment collections
;; =============================================================================

(defn- assignments-for-request-where
  [request-id include-ended?]
  (cond->
   [:and
    [:= :request-assignment/request
     request-id]]

    (not
     include-ended?)
    (conj
     [:= :request-assignment/status
      [:lift :active]])))

(defn- assignment-order
  [assignments]
  (->>
   assignments

   (sort-by
    (juxt
     :request-assignment/created-at
     :xt/id))

   vec))

(defn assignments-for-request
  "Returns every current RequestAssignment belonging to Request.

   Results include ended historical assignments and are ordered oldest first,
   with assignment UUID as deterministic tiebreaker."
  [ctx request-id]
  (if
   (uuid?
    request-id)
    (assignment-order
     (rows
      request.schema/request-assignment-descriptor
      ctx
      {:select
       request-assignment-document-columns

       :from
       [request/assignment-entity-type]

       :where
       (assignments-for-request-where
        request-id
        true)}))
    []))

(defn active-assignments-for-request
  "Returns all active RequestAssignments belonging to Request.

   Results are ordered oldest first."
  [ctx request-id]
  (if
   (uuid?
    request-id)
    (assignment-order
     (rows
      request.schema/request-assignment-descriptor
      ctx
      {:select
       request-assignment-document-columns

       :from
       [request/assignment-entity-type]

       :where
       (assignments-for-request-where
        request-id
        false)}))
    []))

(defn active-assignment-for-helper
  "Returns helper-id's one active assignment on Request, or nil.

   Multiple active assignments for the same helper and Request are persisted
   corruption and fail loudly."
  [ctx request-id helper-id]
  (if
   (and
    (uuid?
     request-id)

    (uuid?
     helper-id))
    (let [matches
          (rows
           request.schema/request-assignment-descriptor
           ctx
           {:select
            request-assignment-document-columns

            :from
            [request/assignment-entity-type]

            :where
            [:and
             [:= :request-assignment/request
              request-id]

             [:= :request-assignment/helper
              helper-id]

             [:= :request-assignment/status
              [:lift :active]]]})]
      (case
       (count
        matches)

        0
        nil

        1
        (first
         matches)

        (fail!
         :request.graph/non-unique-active-helper-assignment
         "More than one active RequestAssignment exists for the helper."
         {:request/id
          request-id

          :request-assignment/helper
          helper-id

          :request-assignment/ids
          (mapv
           request/assignment-id
           matches)})))
    nil))

(defn active-primary-assignment-for-request
  "Returns Request's one active primary RequestAssignment, or nil.

   Multiple active primary assignments are persisted corruption."
  [ctx request-id]
  (if
   (uuid?
    request-id)
    (let [matches
          (rows
           request.schema/request-assignment-descriptor
           ctx
           {:select
            request-assignment-document-columns

            :from
            [request/assignment-entity-type]

            :where
            [:and
             [:= :request-assignment/request
              request-id]

             [:= :request-assignment/role
              [:lift :primary]]

             [:= :request-assignment/status
              [:lift :active]]]})]
      (case
       (count
        matches)

        0
        nil

        1
        (first
         matches)

        (fail!
         :request.graph/non-unique-active-primary
         "More than one active primary RequestAssignment exists."
         {:request/id
          request-id

          :request-assignment/ids
          (mapv
           request/assignment-id
           matches)})))
    nil))

;; =============================================================================
;; Location Request collections
;; =============================================================================

(def active-request-predicate
  [:or
   [:= :request/status
    [:lift :open]]

   [:= :request/status
    [:lift :claimed]]

   [:= :request/status
    [:lift :on-the-way]]])

(defn- requests-for-location-where
  [organization-id location-id include-terminal?]
  (cond->
   [:and
    [:= :request/organization
     organization-id]

    [:= :request/location
     location-id]]

    (not
     include-terminal?)
    (conj
     active-request-predicate)))

(defn- newest-request-first
  [left right]
  (let [created-comparison
        (compare
         (:request/created-at
          right)

         (:request/created-at
          left))]
    (if
     (zero?
      created-comparison)
      (compare
       (:xt/id
        right)

       (:xt/id
        left))

      created-comparison)))

(defn requests-for-location
  "Returns the canonical Request collection for one Organization Location.

   input:

     {:organization-id   uuid
      :location-id       uuid
      :include-terminal? boolean}

   Terminal Requests are excluded unless :include-terminal? is exactly true.

   Results are newest first with Request UUID as deterministic tiebreaker.

   This function establishes only persisted Request ownership fields. It does
   not prove that Organization or Location currently exists or is operational;
   those facts belong to Organization."
  [ctx {:keys
        [organization-id
         location-id
         include-terminal?]}]
  (if
   (and
    (uuid?
     organization-id)

    (uuid?
     location-id))
    (->>
     (rows
      request.schema/request-descriptor
      ctx
      {:select
       request-document-columns

       :from
       [request/request-entity-type]

       :where
       (requests-for-location-where
        organization-id
        location-id
        (true?
         include-terminal?))})

     (sort
      newest-request-first)

     vec)
    []))

;; =============================================================================
;; Active-assignment consistency
;; =============================================================================

(defn- require-assignment-for-request!
  [request-document assignment]
  (request/require-assignment-document
   assignment)

  (when-not
   (request/assignment-for-request?
    assignment
    (request/request-id
     request-document))
    (fail!
     :request.graph/assignment-request-mismatch
     "A Request snapshot contains an assignment belonging to another Request."
     {:request/id
      (request/request-id
       request-document)

      :request-assignment/id
      (request/assignment-id
       assignment)

      :request-assignment/request
      (request/assignment-request-id
       assignment)}))

  (when-not
   (request/assignment-active?
    assignment)
    (fail!
     :request.graph/inactive-assignment-in-active-set
     "A Request active-assignment read returned an ended assignment."
     {:request/id
      (request/request-id
       request-document)

      :request-assignment/id
      (request/assignment-id
       assignment)

      :request-assignment/status
      (request/assignment-status
       assignment)}))

  assignment)

(defn- require-distinct-active-helpers!
  [request-document assignments]
  (let [helper-ids
        (mapv
         request/assignment-helper-id
         assignments)

        distinct-helper-ids
        (set
         helper-ids)]
    (when-not
     (=
      (count
       helper-ids)

      (count
       distinct-helper-ids))
      (fail!
       :request.graph/duplicate-active-helper
       "A helper has more than one active RequestAssignment."
       {:request/id
        (request/request-id
         request-document)

        :request-assignment/helper-ids
        helper-ids})))

  assignments)

(defn- require-lifecycle-assignment-consistency!
  [request-document assignments]
  (let [primary
        (request/active-primary-assignment
         assignments)]

    (cond
      (request/open?
       request-document)
      (when
       (seq
        assignments)
        (fail!
         :request.graph/open-request-has-active-assignments
         "An open Request must not have active RequestAssignments."
         {:request/id
          (request/request-id
           request-document)

          :request/active-assignment-ids
          (mapv
           request/assignment-id
           assignments)}))

      (request/lifecycle-expects-primary-assignment?
       request-document)
      (when-not
       primary
        (fail!
         :request.graph/missing-active-primary
         "The Request lifecycle requires an active primary RequestAssignment."
         {:request/id
          (request/request-id
           request-document)

          :request/status
          (request/request-status
           request-document)}))

      (request/terminal?
       request-document)
      (when
       (seq
        assignments)
        (fail!
         :request.graph/terminal-request-has-active-assignments
         "A terminal Request must not have active RequestAssignments."
         {:request/id
          (request/request-id
           request-document)

          :request/status
          (request/request-status
           request-document)

          :request/active-assignment-ids
          (mapv
           request/assignment-id
           assignments)})))

    primary))

(defn- active-assignment-state
  [request-document assignments]
  (request/require-request-document
   request-document)

  (let [assignments
        (mapv
         #(require-assignment-for-request!
           request-document
           %)
         assignments)

        _
        (require-distinct-active-helpers!
         request-document
         assignments)

        primary
        (require-lifecycle-assignment-consistency!
         request-document
         assignments)]

    {:assignments
     assignments

     :primary-assignment
     primary

     :active-helper-ids
     (request/active-helper-ids
      assignments)

     :active-collaborator-helper-ids
     (request/active-collaborator-helper-ids
      assignments)}))

;; =============================================================================
;; Request snapshots
;; =============================================================================

(defn request-snapshot-from-document
  "Builds Request's authoritative Request-owned active-assignment snapshot from
   an already-loaded Request document.

   The returned state is internally consistent across the Request and all
   current active RequestAssignments.

   This does not establish Organization scope state or helper authorization."
  [ctx request-document]
  (request/require-request-document
   request-document)

  (let [assignments
        (active-assignments-for-request
         ctx
         (request/request-id
          request-document))

        {:keys
         [primary-assignment
          active-helper-ids
          active-collaborator-helper-ids]}
        (active-assignment-state
         request-document
         assignments)]

    {:request
     request-document

     :assignments
     assignments

     :primary-assignment
     primary-assignment

     :active-helper-ids
     active-helper-ids

     :active-collaborator-helper-ids
     active-collaborator-helper-ids}))

(defn request-snapshot
  "Returns Request plus its authoritative active RequestAssignment state.

   Returns nil when Request does not exist.

   A present Request with inconsistent Request-owned assignment state is an
   error rather than a partial snapshot."
  [ctx request-id]
  (when-let [request-document
             (request-document
              ctx
              request-id)]
    (request-snapshot-from-document
     ctx
     request-document)))

(defn require-request-snapshot
  "Returns Request's current Request-owned snapshot or throws when Request does
   not exist."
  [ctx request-id]
  (or
   (request-snapshot
    ctx
    request-id)

   (fail!
    :request/not-found
    "The Request does not exist."
    {:request/id
     request-id})))

;; =============================================================================
;; Location snapshots
;; =============================================================================

(defn request-snapshots-for-location
  "Returns canonical Location Requests enriched only with Request-owned active
   assignment state.

   Organization hierarchy, operational state, Memberships, helper roles, and
   User display data are deliberately absent."
  [ctx input]
  (mapv
   #(request-snapshot-from-document
     ctx
     %)
   (requests-for-location
    ctx
    input)))

;; =============================================================================
;; Request derived Graph facts
;; =============================================================================

(def request-lifecycle-query
  [[:? :request/open?]
   [:? :request/claimed?]
   [:? :request/on-the-way?]
   [:? :request/done?]
   [:? :request/cancelled?]
   [:? :request/active?]
   [:? :request/terminal?]
   [:? :request/editable?]
   [:? :request/claimable?]
   [:? :request/unclaimable?]
   [:? :request/markable-on-the-way?]
   [:? :request/completable?]
   [:? :request/cancellable?]
   [:? :request/expects-primary-assignment?]])

(def request-lifecycle-resolver
  (graph/resolver
   {:id
    ::request-lifecycle

    :input
    [{:request/doc
      request-document-query}]

    :output
    request-lifecycle-query

    :resolve-fn
    (fn [_ctx {:request/keys
               [doc]}]
      (request/require-request-document
       doc)

      {:request/open?
       (request/open?
        doc)

       :request/claimed?
       (request/claimed?
        doc)

       :request/on-the-way?
       (request/on-the-way?
        doc)

       :request/done?
       (request/done?
        doc)

       :request/cancelled?
       (request/cancelled?
        doc)

       :request/active?
       (request/active?
        doc)

       :request/terminal?
       (request/terminal?
        doc)

       :request/editable?
       (request/editable?
        doc)

       :request/claimable?
       (request/claimable?
        doc)

       :request/unclaimable?
       (request/unclaimable?
        doc)

       :request/markable-on-the-way?
       (request/markable-on-the-way?
        doc)

       :request/completable?
       (request/completable?
        doc)

       :request/cancellable?
       (request/cancellable?
        doc)

       :request/expects-primary-assignment?
       (request/lifecycle-expects-primary-assignment?
        doc)})}))

;; =============================================================================
;; RequestAssignment derived Graph facts
;; =============================================================================

(def request-assignment-derived-query
  [[:? :request-assignment/assigned-at]
   [:? :request-assignment/active?]
   [:? :request-assignment/ended?]
   [:? :request-assignment/primary?]
   [:? :request-assignment/collaborator?]
   [:? :request-assignment/active-primary?]
   [:? :request-assignment/active-collaborator?]])

(def request-assignment-derived-resolver
  (graph/resolver
   {:id
    ::request-assignment-derived

    :input
    [{:request-assignment/doc
      request-assignment-document-query}]

    :output
    request-assignment-derived-query

    :resolve-fn
    (fn [_ctx
         {:request-assignment/keys
          [doc]}]
      (request/require-assignment-document
       doc)

      {:request-assignment/assigned-at
       (request/assignment-assigned-at
        doc)

       :request-assignment/active?
       (request/assignment-active?
        doc)

       :request-assignment/ended?
       (request/assignment-ended?
        doc)

       :request-assignment/primary?
       (request/primary-assignment?
        doc)

       :request-assignment/collaborator?
       (request/collaborator-assignment?
        doc)

       :request-assignment/active-primary?
       (request/active-primary-assignment?
        doc)

       :request-assignment/active-collaborator?
       (request/active-collaborator-assignment?
        doc)})}))

;; =============================================================================
;; Request aggregate Assignment Graph facts
;; =============================================================================

(def request-assignment-summary-query
  [[:? :request/has-primary-assignment?]
   [:? :request/primary-assignment-id]
   [:? :request/primary-helper-id]
   [:? :request/active-helper-ids]
   [:? :request/active-collaborator-helper-ids]])

(def request-assignment-summary-resolver
  (graph/resolver
   {:id
    ::request-assignment-summary

    :input
    [{:request/doc
      request-document-query}]

    :output
    request-assignment-summary-query

    :resolve-fn
    (fn [ctx
         {:request/keys
          [doc]}]
      (let [{:keys
             [primary-assignment
              active-helper-ids
              active-collaborator-helper-ids]}
            (request-snapshot-from-document
             ctx
             doc)]

        (cond->
         {:request/has-primary-assignment?
          (boolean
           primary-assignment)

          :request/active-helper-ids
          active-helper-ids

          :request/active-collaborator-helper-ids
          active-collaborator-helper-ids}

          primary-assignment
          (assoc
           :request/primary-assignment-id
           (request/assignment-id
            primary-assignment)

           :request/primary-helper-id
           (request/assignment-helper-id
            primary-assignment)))))}))

;; =============================================================================
;; Custom resolver registry
;; =============================================================================

(def custom-resolvers
  "Request's hand-written Graph contribution.

   gesso.model/build-module supplies conventional by-ID and persisted-field
   resolvers for Request and RequestAssignment. These resolvers add only
   derived lifecycle and Request-owned assignment facts."
  [request-lifecycle-resolver
   request-assignment-derived-resolver
   request-assignment-summary-resolver])
