(ns net.humanhelp.example.chromium-acceptance
  "Real Chromium acceptance for the production-model-backed HumanHelp example app.

   This namespace is intentionally *not* named ...-test. Ordinary JVM tests must
   remain independent of Chromium and of the generated browser artifact. The
   browser gate invokes -main explicitly after building the exact HumanHelp
   gesso-live.js artifact.

   The current scenario covers the Request Claim -> Unclaim -> Claim -> On-the-way -> Complete trajectory plus independent owner Cancel and manager Reassign trajectories and deliberately
   crosses the real joins that the preflight recovery work is meant to protect:

     real HumanHelp Ring middleware / session
       -> real /app render
       -> generated HumanHelp Gesso browser artifact
       -> real HTMX request construction
       -> browser-generated protocol-v3 command
       -> real Claim route
       -> production Request Choreo/model commit
       -> settlement + authoritative reacquisition
       -> persisted claimed reload
       -> real rendered Unclaim control
       -> second browser-generated protocol-v3 command
       -> real Unclaim route
      -> real Claim route again
      -> real Mark-on-the-way route
      -> real Complete route
       -> production Request Choreo/model commits
       -> settlement + authoritative reacquisition
       -> persisted terminal reload
       -> independent owner Cancel route
       -> authoritative cancelled reload
       -> independent manager Reassign route selected through the real target-helper dropdown
       -> authoritative reassignment + persisted reload

   The test seeds only authoritative prerequisite data (Users, helper/manager authority,
   one target helper, one requestor-owned open production Request, one helper-owned open Request for owner cancellation, and one additional open Request for reassignment). It never constructs, injects, or edits
   __gesso_live_optimistic_command. Every lifecycle command observed on the wire
   must have been generated by the browser runtime itself."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.string :as str]
   [clojure.test :refer [deftest is run-tests testing]]
   [com.biffweb.core :as biff.core]
   [gesso.live.application-preflight :as application-preflight]
   [gesso.live.consistency.xtdb :as xtdb-live]
   [gesso.live.optimistic.protocol :as optimistic.protocol]
   [gesso.live.progression.http :as progression.http]
   [gesso.model.command :as model.command]
   [gesso.model.tx :as model.tx]
   [net.humanhelp :as humanhelp]
   [net.humanhelp.components.phone-auth.sms :as phone-auth.sms]
   [net.humanhelp.example.app :as example.app]
   [net.humanhelp.example.routes :as routes]
   [net.humanhelp.site.mock-data :as mock-data]
   [net.humanhelp.site.model.membership.domain :as membership.domain]
   [net.humanhelp.site.model.organization.core :as organization]
   [net.humanhelp.site.model.request.choreo :as request.choreo]
   [net.humanhelp.site.model.request.core :as request]
   [net.humanhelp.site.model.user.domain :as user.domain]
   [ring.middleware.session.memory :as session.memory]
   [xtdb.node :as xtn])
  (:import
   (com.microsoft.playwright
    Browser
    BrowserContext
    BrowserType$LaunchOptions
    ConsoleMessage
    Page
    Playwright
    Playwright$CreateOptions
    Request
    Response
    Route
    Route$FulfillOptions
    WebError)
   (java.io File)
   (java.net ServerSocket URI URLDecoder)
   (java.nio.charset StandardCharsets)
   (java.time Instant)
   (java.util UUID)
   (java.util.function Consumer)))

;; =============================================================================
;; Stable scenario values
;; =============================================================================

(def ^:private helper-id
  (UUID/fromString "a1000000-0000-0000-0000-000000000679"))

(def ^:private requestor-id
  (UUID/fromString "a2000000-0000-0000-0000-000000000679"))

(def ^:private helper-membership-id
  (UUID/fromString "a3000000-0000-0000-0000-000000000679"))

(def ^:private helper-role-assignment-id
  (UUID/fromString "a4000000-0000-0000-0000-000000000679"))

(def ^:private helper-supervisor-role-assignment-id
  (UUID/fromString "a5000000-0000-0000-0000-000000000690"))

(def ^:private target-helper-id
  (UUID/fromString "a6000000-0000-0000-0000-000000000690"))

(def ^:private target-helper-membership-id
  (UUID/fromString "a7000000-0000-0000-0000-000000000690"))

(def ^:private target-helper-role-assignment-id
  (UUID/fromString "a8000000-0000-0000-0000-000000000690"))

(def ^:private helper-phone
  "2065550679")

(def ^:private helper-e164
  "+12065550679")

(def ^:private auth-code
  "679679")

(def ^:private fixture-time
  (Instant/parse "2026-09-11T12:00:00Z"))

(def ^:private request-title
  "HumanHelp real Chromium Claim acceptance")

(def ^:private request-details
  "This Request exists only to prove the real rendered Claim trajectory.")

(def ^:private request-location-detail
  "Chromium acceptance fixture")

(def ^:private cancel-request-title
  "HumanHelp real Chromium Cancel acceptance")

(def ^:private cancel-request-details
  "This helper-owned Request exists only to prove the real rendered Cancel trajectory.")

(def ^:private cancel-request-location-detail
  "Chromium cancel acceptance fixture")

(def ^:private reassign-request-title
  "HumanHelp real Chromium Reassign acceptance")

(def ^:private reassign-request-details
  "This Request exists only to prove target-helper selection and authoritative reassignment.")

(def ^:private reassign-request-location-detail
  "Chromium reassign acceptance fixture")

(def ^:private default-timeout-ms
  15000)

(def ^:private chromium-candidates
  ["chromium"
   "chromium-browser"
   "google-chrome"
   "google-chrome-stable"])

(def ^:private htmx-resource-candidates
  ["META-INF/resources/webjars/htmx.org/2.0.7/dist/htmx.min.js"
   "META-INF/resources/webjars/htmx.org/2.0.7/dist/htmx.js"])

(def ^:private sse-resource-candidates
  ["META-INF/resources/webjars/htmx-ext-sse/2.2.4/dist/sse.min.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/dist/sse.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/sse.min.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/sse.js"])

(def ^:private htmx-url
  "https://unpkg.com/htmx.org@2.0.7")

(def ^:private sse-url
  "https://cdn.jsdelivr.net/npm/htmx-ext-sse@2.2.4")

;; =============================================================================
;; Errors / small helpers
;; =============================================================================

(defn- acceptance-error
  ([kind message]
   (acceptance-error kind message {}))
  ([kind message data]
   (ex-info
    message
    (merge
     {:error/type :net.humanhelp.example.chromium-acceptance/error
      :error/kind kind}
     data))))

(defn- consumer
  [f]
  (reify Consumer
    (accept [_ value]
      (f value))))

(defn- path-directories
  []
  (let [value (or (System/getenv "PATH") "")
        separator
        (re-pattern
         (java.util.regex.Pattern/quote File/pathSeparator))]
    (if (str/blank? value)
      []
      (str/split value separator -1))))

(defn- executable-path
  [value]
  (let [file (io/file (str value))]
    (when (and (.isFile ^File file)
               (.canExecute ^File file))
      (.toAbsolutePath (.toPath ^File file)))))

(defn- command-path
  [command]
  (some
   (fn [directory]
     (executable-path
      (io/file
       (if (str/blank? directory) "." directory)
       command)))
   (path-directories)))

(defn- chromium-executable
  []
  (let [override
        (or
         (some-> (System/getenv "HUMANHELP_CHROMIUM") str/trim not-empty)
         (some-> (System/getenv "GESSO_CHROMIUM") str/trim not-empty))]
    (if override
      (or
       (executable-path override)
       (command-path override)
       (throw
        (acceptance-error
         :invalid-chromium-override
         "Configured Chromium executable is unavailable."
         {:override override})))
      (or
       (some command-path chromium-candidates)
       (throw
        (acceptance-error
         :chromium-not-found
         "HumanHelp Chromium acceptance requires system Chromium/Chrome or HUMANHELP_CHROMIUM."
         {:checked chromium-candidates}))))))

(defn- available-port
  []
  (with-open [socket (ServerSocket. 0)]
    (.getLocalPort socket)))

(defn- uri-path
  [url]
  (.getPath (URI/create url)))

(defn- decode-form-component
  [value]
  (URLDecoder/decode
   (str (or value ""))
   (.name StandardCharsets/UTF_8)))

(defn- encoded-form-params
  [post-data]
  (into
   {}
   (map
    (fn [pair]
      (let [[k v]
            (str/split pair #"=" 2)]
        [(decode-form-component k)
         (decode-form-component v)])))
   (remove str/blank?
           (str/split (or post-data "") #"&"))))

(defn- eventually
  ([pred]
   (eventually 10000 pred))
  ([timeout-ms pred]
   (let [deadline (+ (System/currentTimeMillis) timeout-ms)]
     (loop []
       (let [value
             (try
               (pred)
               (catch Throwable _
                 nil))]
         (cond
           value
           value

           (< (System/currentTimeMillis) deadline)
           (do
             (Thread/sleep 25)
             (recur))

           :else
           nil))))))

;; =============================================================================
;; Deterministic authoritative fixture
;; =============================================================================

(defn- user-command
  [{:keys [id phone email display-name]}]
  (user.domain/create-user-command
   (cond->
    {:id id
     :display-name display-name
     :now fixture-time}
     phone
     (assoc
      :phone phone
      :phone-verified? true)

     email
     (assoc
      :email email
      :email-verified? true))))

(defn- seed-users!
  [ctx]
  (model.tx/transact!
   ctx
   {:commands
    [(user-command
      {:id helper-id
       :phone helper-e164
       :display-name "Chromium Helper"})

     (user-command
      {:id requestor-id
       :email "chromium-requestor@example.com"
       :display-name "Chromium Requestor"})

     (user-command
      {:id target-helper-id
       :email "chromium-target-helper@example.com"
       :display-name "Chromium Target Helper"})]

    :emit false}))

(defn- seed-helper-authority!
  [ctx]
  (let [membership-command
        (membership.domain/create-membership-command
         {:id helper-membership-id
          :user-id helper-id
          :organization-id mock-data/organization-id
          :now fixture-time})

        membership-document
        (model.command/after membership-command)

        role-command
        (membership.domain/create-role-assignment-command
         membership-document
         {:id helper-role-assignment-id
          :role :helper
          :scope
          (organization/location-scope
           mock-data/default-location-id)
          :now fixture-time})

        supervisor-command
        (membership.domain/create-role-assignment-command
         membership-document
         {:id helper-supervisor-role-assignment-id
          :role :supervisor
          :scope
          (organization/location-scope
           mock-data/default-location-id)
          :now fixture-time})]
    (model.tx/transact!
     ctx
     {:commands [membership-command role-command supervisor-command]
      :emit false})))

(defn- seed-target-helper-authority!
  [ctx]
  (let [membership-command
        (membership.domain/create-membership-command
         {:id target-helper-membership-id
          :user-id target-helper-id
          :organization-id mock-data/organization-id
          :now fixture-time})

        membership-document
        (model.command/after membership-command)

        role-command
        (membership.domain/create-role-assignment-command
         membership-document
         {:id target-helper-role-assignment-id
          :role :helper
          :scope
          (organization/location-scope
           mock-data/default-location-id)
          :now fixture-time})]
    (model.tx/transact!
     ctx
     {:commands [membership-command role-command]
      :emit false})))

(defn- create-open-request!
  [ctx]
  (request/create
   (assoc
    ctx
    :current-user/id requestor-id
    :biff.fx/now fixture-time
    :biff.fx/seed 679)
   {:organization-id mock-data/organization-id
    :location-id mock-data/default-location-id
    :content
    {:title request-title
     :details request-details
     :location-detail request-location-detail}}))

(defn- create-helper-open-request!
  [ctx]
  (request/create
   (assoc
    ctx
    :current-user/id helper-id
    :biff.fx/now fixture-time
    :biff.fx/seed 687)
   {:organization-id mock-data/organization-id
    :location-id mock-data/default-location-id
    :content
    {:title cancel-request-title
     :details cancel-request-details
     :location-detail cancel-request-location-detail}}))

(defn- create-reassign-open-request!
  [ctx]
  (request/create
   (assoc
    ctx
    :current-user/id requestor-id
    :biff.fx/now fixture-time
    :biff.fx/seed 690)
   {:organization-id mock-data/organization-id
    :location-id mock-data/default-location-id
    :content
    {:title reassign-request-title
     :details reassign-request-details
     :location-detail reassign-request-location-detail}}))

(defn- seed-scenario!
  [system]
  (let [seed-ctx
        (assoc
         system
         :biff.fx/now fixture-time
         :biff.fx/seed 679)

        users-transaction
        (seed-users! seed-ctx)

        users-ctx
        (:ctx users-transaction)

        fixture-result
        (mock-data/ensure! users-ctx)

        fixture-ctx
        (:ctx fixture-result)

        helper-transaction
        (seed-helper-authority! fixture-ctx)

        helper-ctx
        (:ctx helper-transaction)

        target-helper-transaction
        (seed-target-helper-authority! helper-ctx)

        target-helper-ctx
        (:ctx target-helper-transaction)

        create-result
        (create-open-request! target-helper-ctx)

        cancel-create-result
        (create-helper-open-request! target-helper-ctx)

        reassign-create-result
        (create-reassign-open-request! target-helper-ctx)]
    {:ctx target-helper-ctx
     :request (:request create-result)
     :create-result create-result
     :cancel-request (:request cancel-create-result)
     :cancel-create-result cancel-create-result
     :reassign-request (:request reassign-create-result)
     :reassign-create-result reassign-create-result}))

;; =============================================================================
;; Actual HumanHelp runtime
;; =============================================================================

(defn- start-runtime!
  []
  (let [port
        (available-port)

        base-url
        (str "http://127.0.0.1:" port)

        node
        (xtn/start-node {})]
    (try
      (let [application-assembly
            (humanhelp/require-application-assembly!)

            initial-system
            (merge
             humanhelp/initial-system
             {:biff.xtdb/node node
              :biff.ring/host "127.0.0.1"
              :biff.ring/port port
              :biff.ring/base-url base-url
              :biff.ring/secure false
              :biff.ring/ssl-redirect false
              :biff.ring/fallback-session-store
              (session.memory/memory-store)
              :biff.core/stop
              [(fn []
                 (.close node))]})

            system
            (application-preflight/start-biff-application!
             application-assembly
             initial-system
             #'humanhelp/modules
             [humanhelp/use-gesso-live
              humanhelp/use-aleph])]
        {:system system
         :base-url base-url})
      (catch Throwable error
        (try
          (.close node)
          (catch Throwable _))
        (throw error)))))

(defn- stop-runtime!
  [{:keys [system]}]
  (when system
    (biff.core/stop system))
  nil)

;; =============================================================================
;; Browser control / diagnostics
;; =============================================================================

(defn- start-browser!
  []
  (let [chromium-path
        (chromium-executable)

        create-options
        (doto (Playwright$CreateOptions.)
          (.setEnv
           (assoc
            (into {} (System/getenv))
            "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD"
            "1")))

        playwright
        (Playwright/create create-options)]
    (try
      (let [launch-options
            (doto (BrowserType$LaunchOptions.)
              (.setExecutablePath chromium-path)
              (.setHeadless true)
              (.setTimeout 20000.0))

            browser
            (.launch (.chromium playwright) launch-options)]
        {:playwright playwright
         :browser browser
         :chromium-executable chromium-path})
      (catch Throwable error
        (.close playwright)
        (throw error)))))

(defn- stop-browser!
  [{:keys [^Browser browser ^Playwright playwright]}]
  (when browser
    (.close browser))
  (when playwright
    (.close playwright))
  nil)

(defn- resource-text
  [candidates]
  (some-> (some io/resource candidates)
          slurp))

(defn- fulfill!
  [^Route route content-type body]
  (.fulfill
   route
   (doto (Route$FulfillOptions.)
     (.setStatus 200)
     (.setContentType content-type)
     (.setBody body))))

(defn- install-local-browser-assets!
  "Use pinned local HTMX/SSE bytes when the browser-test classpath supplies
   them (for example in Gesso's development/test environment). When unavailable,
   leave the application's real CDN request untouched instead of silently
   substituting a different implementation."
  [^BrowserContext context]
  (when-let [htmx (resource-text htmx-resource-candidates)]
    (.route
     context
     htmx-url
     (consumer
      #(fulfill! % "text/javascript; charset=utf-8" htmx))))

  (when-let [sse (resource-text sse-resource-candidates)]
    (.route
     context
     sse-url
     (consumer
      #(fulfill! % "text/javascript; charset=utf-8" sse))))

  ;; These assets are presentation/optional behavior outside the Claim protocol
  ;; being accepted here. Keep the real URLs in application markup, but make the
  ;; headless test independent of unrelated CDN availability.
  (.route
   context
   "https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/basecoat.cdn.min.css"
   (consumer #(fulfill! % "text/css; charset=utf-8" "")))

  (.route
   context
   "https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/js/all.min.js"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://unpkg.com/htmx-ext-ws@2.0.2/ws.js"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://unpkg.com/hyperscript.org@0.9.14"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://fonts.googleapis.com/**"
   (consumer #(fulfill! % "text/css; charset=utf-8" "")))

  context)

(defn- new-browser-context!
  [{:keys [^Browser browser]}]
  (let [context
        (.newContext browser)

        diagnostics
        (atom
         {:console-errors []
          :web-errors []
          :request-failures []
          :claim-requests []
          :claim-responses []
          :unclaim-requests []
          :unclaim-responses []
          :mark-on-the-way-requests []
          :mark-on-the-way-responses []
          :complete-requests []
          :complete-responses []
          :cancel-requests []
          :cancel-responses []
          :reassign-requests []
          :reassign-responses []
          :request-list-fragment-requests []
          :request-list-fragment-responses []})]

    (.setDefaultTimeout context (double default-timeout-ms))
    (.setDefaultNavigationTimeout context (double default-timeout-ms))

    (.onConsoleMessage
     context
     (consumer
      (fn [^ConsoleMessage message]
        (when (#{"error" "assert"} (.type message))
          (swap!
           diagnostics
           update
           :console-errors
           conj
           {:type (.type message)
            :text (.text message)})))))

    (.onWebError
     context
     (consumer
      (fn [^WebError error]
        (swap!
         diagnostics
         update
         :web-errors
         conj
         {:error (.error error)}))))

    (.onRequestFailed
     context
     (consumer
      (fn [^Request request]
        (swap!
         diagnostics
         update
         :request-failures
         conj
         {:method (.method request)
          :url (.url request)
          :failure (.failure request)}))))

    (.onRequest
     context
     (consumer
      (fn [^Request request]
        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/claim"))
          (swap!
           diagnostics
           update
           :claim-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/unclaim"))
          (swap!
           diagnostics
           update
           :unclaim-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/mark-on-the-way"))
          (swap!
           diagnostics
           update
           :mark-on-the-way-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/complete"))
          (swap!
           diagnostics
           update
           :complete-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/cancel"))
          (swap!
           diagnostics
           update
           :cancel-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/reassign"))
          (swap!
           diagnostics
           update
           :reassign-requests
           conj
           {:url (.url request)
            :post-data (.postData request)}))

        (when (and
               (= "GET" (.method request))
               (= (routes/request-list-fragment-url)
                  (uri-path (.url request))))
          (swap!
           diagnostics
           update
           :request-list-fragment-requests
           conj
           {:url (.url request)
            :headers (into {} (.allHeaders request))})))))

    (.onResponse
     context
     (consumer
      (fn [^Response response]
        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/claim"))
          (swap!
           diagnostics
           update
           :claim-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/unclaim"))
          (swap!
           diagnostics
           update
           :unclaim-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/mark-on-the-way"))
          (swap!
           diagnostics
           update
           :mark-on-the-way-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/complete"))
          (swap!
           diagnostics
           update
           :complete-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/cancel"))
          (swap!
           diagnostics
           update
           :cancel-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/reassign"))
          (swap!
           diagnostics
           update
           :reassign-responses
           conj
           {:url (.url response)
            :status (.status response)}))

        (when (and
               (= "GET" (.method (.request response)))
               (= (routes/request-list-fragment-url)
                  (uri-path (.url response))))
          (swap!
           diagnostics
           update
           :request-list-fragment-responses
           conj
           {:url (.url response)
            :status (.status response)})))))

    (install-local-browser-assets! context)

    {:context context
     :diagnostics diagnostics}))

(defn- close-browser-context!
  [{:keys [^BrowserContext context]}]
  (when context
    (.close context))
  nil)

(defn- clean-browser-diagnostics?
  [{:keys [console-errors web-errors request-failures]}]
  (and
   (empty? console-errors)
   (empty? web-errors)
   (empty? request-failures)))

;; =============================================================================
;; Actual browser actions
;; =============================================================================

(def ^:private generate-code-var
  (ns-resolve
   'net.humanhelp.components.phone-auth.sms
   'generate-code))

(defn- sign-in!
  [^Page page base-url]
  (.navigate page (str base-url "/"))

  (let [phone-input
        (.locator page "#phone-display")]
    (.waitFor phone-input)
    (.fill phone-input helper-phone)
    (.click
     (.locator
      page
      "#phone-auth-send-form button[type=\"submit\"]")))

  (let [code-input
        (.locator page "#code")]
    (.waitFor code-input)
    (.fill code-input auth-code)
    (.click
     (.locator
      page
      "#phone-auth-verify-form button[type=\"submit\"]")))

  (.waitForURL
   page
   (reify java.util.function.Predicate
     (test [_ url]
       (= "/app" (uri-path url)))))

  page)

(defn- claim-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"claim\"]"))

(defn- request-summary-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-summary]"))

(defn- unclaim-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"unclaim\"]"))

(defn- mark-on-the-way-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"mark-on-the-way\"]"))

(defn- complete-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"complete\"]"))

(defn- cancel-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"cancel\"]"))

(defn- reassign-trigger-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-reassign-trigger]"))

(defn- reassign-target-selector
  [request-id helper-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"reassign\"]"
   "[data-humanhelp-request-reassign-helper-id=\""
   helper-id
   "\"]"))

(defn- claim-through-browser!
  [^Page page request-id]
  (let [claim-button
        (.locator page (claim-button-selector request-id))]
    (.waitFor claim-button)

    (when-not (.isVisible claim-button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click claim-button))

  request-id)

(defn- unclaim-through-browser!
  [^Page page request-id]
  (let [unclaim-button
        (.locator page (unclaim-button-selector request-id))]
    (.waitFor unclaim-button)

    (when-not (.isVisible unclaim-button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click unclaim-button))

  request-id)

(defn- mark-on-the-way-through-browser!
  [^Page page request-id]
  (let [button
        (.locator page (mark-on-the-way-button-selector request-id))]
    (.waitFor button)

    (when-not (.isVisible button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click button))

  request-id)

(defn- complete-through-browser!
  [^Page page request-id]
  (let [button
        (.locator page (complete-button-selector request-id))]
    (.waitFor button)

    (when-not (.isVisible button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click button))

  request-id)

(defn- cancel-through-browser!
  [^Page page request-id]
  (let [button
        (.locator page (cancel-button-selector request-id))]
    (.waitFor button)

    (when-not (.isVisible button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click button))

  request-id)

(defn- reassign-through-browser!
  [^Page page request-id target-helper-id]
  (let [trigger
        (.locator page (reassign-trigger-selector request-id))

        target
        (.locator page (reassign-target-selector request-id target-helper-id))]
    (.waitFor trigger)

    (when-not (.isVisible trigger)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click trigger)
    (.waitFor target)
    (.click target))

  request-id)

(defn- wait-for-authoritative-status!
  [system request-id expected-status]
  (eventually
   default-timeout-ms
   (fn []
     (let [request-document
           (request/request system request-id)]
       (when (= expected-status (some-> request-document request/status))
         request-document)))))

(defn- wait-for-authoritative-claim!
  [system request-id]
  (wait-for-authoritative-status! system request-id :claimed))

(defn- wait-for-authoritative-unclaim!
  [system request-id]
  (wait-for-authoritative-status! system request-id :open))

(defn- wait-for-authoritative-on-the-way!
  [system request-id]
  (wait-for-authoritative-status! system request-id :on-the-way))

(defn- wait-for-authoritative-done!
  [system request-id]
  (wait-for-authoritative-status! system request-id :done))

(defn- wait-for-authoritative-cancelled!
  [system request-id]
  (wait-for-authoritative-status! system request-id :cancelled))

(defn- authoritative-primary-helper-id
  [system request-id]
  (some->
   (request/active-primary-assignment-for-request system request-id)
   request/assignment-helper-id))

(defn- wait-for-authoritative-primary-helper!
  [system request-id expected-helper-id]
  (eventually
   default-timeout-ms
   #(when
      (= expected-helper-id
         (authoritative-primary-helper-id system request-id))
      expected-helper-id)))

(defn- wait-for-claimed-dom!
  [^Page page request-id]
  (let [unclaim-button
        (.locator page (unclaim-button-selector request-id))]
    (.waitFor unclaim-button)
    unclaim-button))

(defn- wait-for-open-dom!
  [^Page page request-id]
  (let [claim-button
        (.locator page (claim-button-selector request-id))]
    (eventually
     default-timeout-ms
     #(when (= 1 (.count claim-button)) claim-button))))

(defn- wait-for-mark-on-the-way-dom!
  [^Page page request-id]
  (let [button
        (.locator page (mark-on-the-way-button-selector request-id))]
    (eventually
     default-timeout-ms
     #(when (= 1 (.count button)) button))))

(defn- wait-for-on-the-way-dom!
  [^Page page request-id]
  (let [button
        (.locator page (complete-button-selector request-id))]
    (eventually
     default-timeout-ms
     #(when (= 1 (.count button)) button))))

(defn- request-card-selector
  [request-id]
  (str "#humanhelp-request-" request-id))

(defn- wait-for-request-card-absent!
  [^Page page request-id]
  (let [request-card
        (.locator page (request-card-selector request-id))]
    (eventually
     default-timeout-ms
     #(when (zero? (.count request-card)) true))))

(defn- decode-rendered-action
  [locator]
  (some-> (.getAttribute locator "data-gesso-live-optimistic")
          edn/read-string))

(defn- progression-bearing-request-list-refresh
  [diagnostics start-index]
  (some
   (fn [{:keys [headers] :as request}]
     (when-let [encoded
                (get headers progression.http/request-header-name)]
       (assoc
        request
        :progression
        (progression.http/decode-request-progression encoded))))
   (drop start-index
         (:request-list-fragment-requests @diagnostics))))

(defn- successful-request-list-response-after?
  [diagnostics start-index]
  (some
   (fn [{:keys [status] :as response}]
     (when (< status 400)
       response))
   (drop start-index
         (:request-list-fragment-responses @diagnostics))))

;; =============================================================================
;; Claim acceptance
;; =============================================================================

(deftest real-rendered-claim-crosses-browser-runtime-and-persists-test
  (let [runtime
        (start-runtime!)]
    (try
      (let [{:keys [system base-url]}
            runtime

            {:keys [request cancel-request reassign-request]}
            (seed-scenario! system)

            request-id
            (request/request-id request)

            cancel-request-id
            (request/request-id cancel-request)

            reassign-request-id
            (request/request-id reassign-request)

            browser
            (start-browser!)

            browser-context
            (new-browser-context! browser)]
        (try
          (let [^BrowserContext context
                (:context browser-context)

                ^Page page
                (.newPage context)]
            (with-redefs-fn
              {generate-code-var
               (fn [_length]
                 auth-code)}
              (fn []
                (sign-in! page base-url)

                (let [claim-button
                      (.locator page (claim-button-selector request-id))

                      encoded-rendered-action
                      (.getAttribute
                       claim-button
                       "data-gesso-live-optimistic")

                      rendered-action
                      (some-> encoded-rendered-action edn/read-string)

                      initial-observed-basis
                      (:observed-basis rendered-action)

                      fragment-request-start
                      (count
                       (:request-list-fragment-requests
                        @(:diagnostics browser-context)))

                      fragment-response-start
                      (count
                       (:request-list-fragment-responses
                        @(:diagnostics browser-context)))]
                  (testing "the authoritative initial /app render exposes a real semantic Claim control"
                    (is (= 1
                           (.count claim-button)))
                    (is (= :open
                           (request/status
                            (request/require-request system request-id)))))

                  (testing "the server render carries semantic action data but no browser-owned correlation identity"
                    (is (string? encoded-rendered-action))
                    (is (= request.choreo/claim-operation
                           (:operation rendered-action)))
                    (is (= {:request-id request-id}
                           (:arguments rendered-action)))
                    (is (some? (:observed-basis rendered-action)))
                    (is (not (contains? rendered-action :command-id)))
                    (is (not (contains? rendered-action :execution-id))))

                  (claim-through-browser! page request-id)

                  (testing "the browser, not the test, adds protocol-v3 correlation identity and preserves the rendered semantics"
                    (is
                     (eventually
                      default-timeout-ms
                      #(first (:claim-requests @(:diagnostics browser-context))))
                     (pr-str @(:diagnostics browser-context)))

                    (let [claim-request
                          (first (:claim-requests @(:diagnostics browser-context)))

                          params
                          (encoded-form-params (:post-data claim-request))

                          encoded-command
                          (get params example.app/optimistic-command-param)

                          command
                          (some-> encoded-command
                                  edn/read-string
                                  optimistic.protocol/wire->command)]
                      (is (string? encoded-command)
                          "The real HTMX POST must contain the browser-generated optimistic command parameter.")
                      (is (= (:operation rendered-action)
                             (:operation command)))
                      (is (= (:arguments rendered-action)
                             (:arguments command)))
                      (is (= (:observed-basis rendered-action)
                             (:observed-basis command)))
                      (is (= (:scope rendered-action)
                             (:scope command)))
                      (is (= (:fact-versions rendered-action)
                             (:fact-versions command)))
                      (is (some? (:command-id command)))
                      (is (some? (:execution-id command)))))

                (testing "the real server path commits Claim authoritatively"
                  (is (some?
                       (wait-for-authoritative-claim!
                        system
                        request-id))
                      (pr-str @(:diagnostics browser-context)))
                  (is
                   (eventually
                    default-timeout-ms
                    #(some
                      (fn [{:keys [status]}]
                        (when (< status 400) status))
                      (:claim-responses @(:diagnostics browser-context))))
                   (pr-str @(:diagnostics browser-context))))

                (testing "settlement/reacquisition performs a progression-bearing authoritative Request-list reread"
                  (is
                   (eventually
                    default-timeout-ms
                    #(progression-bearing-request-list-refresh
                      (:diagnostics browser-context)
                      fragment-request-start))
                   (pr-str @(:diagnostics browser-context)))
                  (is
                   (eventually
                    default-timeout-ms
                    #(successful-request-list-response-after?
                      (:diagnostics browser-context)
                      fragment-response-start))
                   (pr-str @(:diagnostics browser-context))))

                (testing "canonical reread replaces provisional ownership with a newer authoritative Claim frontier"
                  (let [unclaim-button
                        (wait-for-claimed-dom! page request-id)

                        request-card
                        (.locator page (request-card-selector request-id))

                        refresh-request
                        (progression-bearing-request-list-refresh
                         (:diagnostics browser-context)
                         fragment-request-start)

                        required-basis
                        (some-> refresh-request
                                :progression
                                xtdb-live/strongest-required-basis)

                        unclaim-action
                        (decode-rendered-action unclaim-button)

                        canonical-basis
                        (:observed-basis unclaim-action)]
                    (is (some? unclaim-button)
                        (pr-str @(:diagnostics browser-context)))
                    (is (nil?
                         (.getAttribute
                          request-card
                          "data-gesso-optimistic-provisional"))
                        "Canonical Request-list replacement must retire Gesso provisional ownership.")
                    (is (= request.choreo/unclaim-operation
                           (:operation unclaim-action)))
                    (is (some? required-basis)
                        (pr-str refresh-request))
                    (is (some? canonical-basis)
                        (pr-str unclaim-action))
                    (is (and
                         (some? required-basis)
                         (some? canonical-basis)
                         (not
                          (pos?
                           (xtdb-live/compare-bases
                            required-basis
                            canonical-basis))))
                        "The canonical Unclaim affordance must be rendered from an authoritative frontier satisfying the Live-requested minimum.")
                    (is (and
                         (some? initial-observed-basis)
                         (some? canonical-basis)
                         (xtdb-live/basis-advances?
                          initial-observed-basis
                          canonical-basis))
                        "The post-Claim canonical basis must strictly advance the initial rendered Claim basis.")))

                (testing "reload reconstructs the claimed state from authority rather than provisional DOM"
                  (.reload page)
                  (is (some?
                       (wait-for-claimed-dom! page request-id)))
                  (is (= :claimed
                         (request/status
                          (request/require-request system request-id)))))

                (let [unclaim-button
                      (wait-for-claimed-dom! page request-id)

                      rendered-unclaim-action
                      (decode-rendered-action unclaim-button)

                      pre-unclaim-basis
                      (:observed-basis rendered-unclaim-action)

                      unclaim-fragment-request-start
                      (count
                       (:request-list-fragment-requests
                        @(:diagnostics browser-context)))

                      unclaim-fragment-response-start
                      (count
                       (:request-list-fragment-responses
                        @(:diagnostics browser-context)))]
                  (testing "the persisted authoritative reload exposes semantic Unclaim without browser-owned correlation identity"
                    (is (= request.choreo/unclaim-operation
                           (:operation rendered-unclaim-action)))
                    (is (= {:request-id request-id}
                           (:arguments rendered-unclaim-action)))
                    (is (some? pre-unclaim-basis))
                    (is (not (contains? rendered-unclaim-action :command-id)))
                    (is (not (contains? rendered-unclaim-action :execution-id))))

                  (unclaim-through-browser! page request-id)

                  (testing "the browser independently creates the protocol-v3 Unclaim command"
                    (is
                     (eventually
                      default-timeout-ms
                      #(first (:unclaim-requests @(:diagnostics browser-context))))
                     (pr-str @(:diagnostics browser-context)))

                    (let [unclaim-request
                          (first (:unclaim-requests @(:diagnostics browser-context)))

                          params
                          (encoded-form-params (:post-data unclaim-request))

                          encoded-command
                          (get params example.app/optimistic-command-param)

                          command
                          (some-> encoded-command
                                  edn/read-string
                                  optimistic.protocol/wire->command)]
                      (is (string? encoded-command)
                          "The real Unclaim POST must contain a browser-generated optimistic command parameter.")
                      (is (= (:operation rendered-unclaim-action)
                             (:operation command)))
                      (is (= (:arguments rendered-unclaim-action)
                             (:arguments command)))
                      (is (= (:observed-basis rendered-unclaim-action)
                             (:observed-basis command)))
                      (is (= (:scope rendered-unclaim-action)
                             (:scope command)))
                      (is (= (:fact-versions rendered-unclaim-action)
                             (:fact-versions command)))
                      (is (some? (:command-id command)))
                      (is (some? (:execution-id command)))))

                  (testing "the real server path commits Unclaim authoritatively"
                    (is (some?
                         (wait-for-authoritative-unclaim!
                          system
                          request-id))
                        (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(some
                        (fn [{:keys [status]}]
                          (when (< status 400) status))
                        (:unclaim-responses @(:diagnostics browser-context))))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "Unclaim settlement performs a progression-bearing authoritative Request-list reread"
                    (is
                     (eventually
                      default-timeout-ms
                      #(progression-bearing-request-list-refresh
                        (:diagnostics browser-context)
                        unclaim-fragment-request-start))
                     (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(successful-request-list-response-after?
                        (:diagnostics browser-context)
                        unclaim-fragment-response-start))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "canonical Unclaim reread returns the Request to an authoritative open frontier"
                    (let [claim-button
                          (wait-for-open-dom! page request-id)

                          request-card
                          (.locator page (request-card-selector request-id))

                          refresh-request
                          (progression-bearing-request-list-refresh
                           (:diagnostics browser-context)
                           unclaim-fragment-request-start)

                          required-basis
                          (some-> refresh-request
                                  :progression
                                  xtdb-live/strongest-required-basis)

                          claim-action
                          (decode-rendered-action claim-button)

                          canonical-open-basis
                          (:observed-basis claim-action)]
                      (is (some? claim-button)
                          (pr-str @(:diagnostics browser-context)))
                      (is (nil?
                           (.getAttribute
                            request-card
                            "data-gesso-optimistic-provisional"))
                          "Canonical Request-list replacement must retire Unclaim provisional ownership.")
                      (is (= request.choreo/claim-operation
                             (:operation claim-action)))
                      (is (some? required-basis)
                          (pr-str refresh-request))
                      (is (some? canonical-open-basis)
                          (pr-str claim-action))
                      (is (and
                           (some? required-basis)
                           (some? canonical-open-basis)
                           (not
                            (pos?
                             (xtdb-live/compare-bases
                              required-basis
                              canonical-open-basis))))
                          "The canonical Claim affordance after Unclaim must satisfy the Live-requested minimum.")
                      (is (and
                           (some? pre-unclaim-basis)
                           (some? canonical-open-basis)
                           (xtdb-live/basis-advances?
                            pre-unclaim-basis
                            canonical-open-basis))
                          "The post-Unclaim canonical basis must strictly advance the authoritative Unclaim render basis.")))

                  (testing "reload reconstructs the open state after Unclaim from persisted authority"
                    (.reload page)
                    (is (some?
                         (wait-for-open-dom! page request-id)))
                    (is (= :open
                           (request/status
                            (request/require-request system request-id))))))

                ;; Reclaim the same authoritative Request so the next lifecycle edge is
                ;; exercised from a state reached entirely through the real browser.
                (claim-through-browser! page request-id)
                (is (some?
                     (wait-for-authoritative-claim! system request-id))
                    (pr-str @(:diagnostics browser-context)))

                (let [mark-button
                      (wait-for-mark-on-the-way-dom! page request-id)

                      rendered-mark-action
                      (decode-rendered-action mark-button)

                      pre-mark-basis
                      (:observed-basis rendered-mark-action)

                      mark-request-start
                      (count
                       (:mark-on-the-way-requests
                        @(:diagnostics browser-context)))

                      mark-response-start
                      (count
                       (:mark-on-the-way-responses
                        @(:diagnostics browser-context)))

                      mark-fragment-request-start
                      (count
                       (:request-list-fragment-requests
                        @(:diagnostics browser-context)))

                      mark-fragment-response-start
                      (count
                       (:request-list-fragment-responses
                        @(:diagnostics browser-context)))]
                  (testing "the reclaimed authoritative state exposes semantic Mark-on-the-way without browser-owned correlation identity"
                    (is (some? mark-button)
                        (pr-str @(:diagnostics browser-context)))
                    (is (= request.choreo/mark-on-the-way-operation
                           (:operation rendered-mark-action)))
                    (is (= {:request-id request-id}
                           (:arguments rendered-mark-action)))
                    (is (some? pre-mark-basis))
                    (is (not (contains? rendered-mark-action :command-id)))
                    (is (not (contains? rendered-mark-action :execution-id))))

                  (mark-on-the-way-through-browser! page request-id)

                  (testing "the browser creates the protocol-v3 Mark-on-the-way command"
                    (is
                     (eventually
                      default-timeout-ms
                      #(when (> (count (:mark-on-the-way-requests
                                       @(:diagnostics browser-context)))
                                mark-request-start)
                         (last (:mark-on-the-way-requests
                                @(:diagnostics browser-context)))))
                     (pr-str @(:diagnostics browser-context)))

                    (let [mark-request
                          (last (:mark-on-the-way-requests
                                 @(:diagnostics browser-context)))

                          params
                          (encoded-form-params (:post-data mark-request))

                          encoded-command
                          (get params example.app/optimistic-command-param)

                          command
                          (some-> encoded-command
                                  edn/read-string
                                  optimistic.protocol/wire->command)]
                      (is (string? encoded-command)
                          "The real Mark-on-the-way POST must contain a browser-generated optimistic command parameter.")
                      (is (= (:operation rendered-mark-action)
                             (:operation command)))
                      (is (= (:arguments rendered-mark-action)
                             (:arguments command)))
                      (is (= (:observed-basis rendered-mark-action)
                             (:observed-basis command)))
                      (is (= (:scope rendered-mark-action)
                             (:scope command)))
                      (is (= (:fact-versions rendered-mark-action)
                             (:fact-versions command)))
                      (is (some? (:command-id command)))
                      (is (some? (:execution-id command)))))

                  (testing "the real server path commits Mark-on-the-way authoritatively"
                    (is (some?
                         (wait-for-authoritative-on-the-way!
                          system
                          request-id))
                        (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(some
                        (fn [{:keys [status]}]
                          (when (< status 400) status))
                        (drop
                         mark-response-start
                         (:mark-on-the-way-responses
                          @(:diagnostics browser-context)))))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "Mark-on-the-way settlement performs a progression-bearing authoritative Request-list reread"
                    (is
                     (eventually
                      default-timeout-ms
                      #(progression-bearing-request-list-refresh
                        (:diagnostics browser-context)
                        mark-fragment-request-start))
                     (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(successful-request-list-response-after?
                        (:diagnostics browser-context)
                        mark-fragment-response-start))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "canonical Mark-on-the-way reread exposes Complete from a newer authoritative frontier"
                    (let [complete-button
                          (wait-for-on-the-way-dom! page request-id)

                          request-card
                          (.locator page (request-card-selector request-id))

                          refresh-request
                          (progression-bearing-request-list-refresh
                           (:diagnostics browser-context)
                           mark-fragment-request-start)

                          required-basis
                          (some-> refresh-request
                                  :progression
                                  xtdb-live/strongest-required-basis)

                          complete-action
                          (decode-rendered-action complete-button)

                          canonical-on-the-way-basis
                          (:observed-basis complete-action)]
                      (is (some? complete-button)
                          (pr-str @(:diagnostics browser-context)))
                      (is (nil?
                           (.getAttribute
                            request-card
                            "data-gesso-optimistic-provisional"))
                          "Canonical Request-list replacement must retire Mark-on-the-way provisional ownership.")
                      (is (= request.choreo/complete-operation
                             (:operation complete-action)))
                      (is (some? required-basis)
                          (pr-str refresh-request))
                      (is (some? canonical-on-the-way-basis)
                          (pr-str complete-action))
                      (is (and
                           (some? required-basis)
                           (some? canonical-on-the-way-basis)
                           (not
                            (pos?
                             (xtdb-live/compare-bases
                              required-basis
                              canonical-on-the-way-basis))))
                          "The canonical Complete affordance must be rendered from an authoritative frontier satisfying the Live-requested minimum.")
                      (is (and
                           (some? pre-mark-basis)
                           (some? canonical-on-the-way-basis)
                           (xtdb-live/basis-advances?
                            pre-mark-basis
                            canonical-on-the-way-basis))
                          "The post-Mark-on-the-way canonical basis must strictly advance the claimed render basis.")))

                  (testing "reload reconstructs the on-the-way state from persisted authority"
                    (.reload page)
                    (is (some?
                         (wait-for-on-the-way-dom! page request-id)))
                    (is (= :on-the-way
                           (request/status
                            (request/require-request system request-id)))))

                  (let [complete-button
                        (wait-for-on-the-way-dom! page request-id)

                        rendered-complete-action
                        (decode-rendered-action complete-button)

                        pre-complete-basis
                        (:observed-basis rendered-complete-action)

                        complete-request-start
                        (count
                         (:complete-requests
                          @(:diagnostics browser-context)))

                        complete-response-start
                        (count
                         (:complete-responses
                          @(:diagnostics browser-context)))

                        complete-fragment-request-start
                        (count
                         (:request-list-fragment-requests
                          @(:diagnostics browser-context)))

                        complete-fragment-response-start
                        (count
                         (:request-list-fragment-responses
                          @(:diagnostics browser-context)))]
                    (testing "the authoritative on-the-way state exposes semantic Complete without browser-owned correlation identity"
                      (is (some? complete-button)
                          (pr-str @(:diagnostics browser-context)))
                      (is (= request.choreo/complete-operation
                             (:operation rendered-complete-action)))
                      (is (= {:request-id request-id}
                             (:arguments rendered-complete-action)))
                      (is (some? pre-complete-basis))
                      (is (not (contains? rendered-complete-action :command-id)))
                      (is (not (contains? rendered-complete-action :execution-id))))

                    (complete-through-browser! page request-id)

                    (testing "the browser creates the protocol-v3 Complete command"
                      (is
                       (eventually
                        default-timeout-ms
                        #(when (> (count (:complete-requests
                                         @(:diagnostics browser-context)))
                                  complete-request-start)
                           (last (:complete-requests
                                  @(:diagnostics browser-context)))))
                       (pr-str @(:diagnostics browser-context)))

                      (let [complete-request
                            (last (:complete-requests
                                   @(:diagnostics browser-context)))

                            params
                            (encoded-form-params (:post-data complete-request))

                            encoded-command
                            (get params example.app/optimistic-command-param)

                            command
                            (some-> encoded-command
                                    edn/read-string
                                    optimistic.protocol/wire->command)]
                        (is (string? encoded-command)
                            "The real Complete POST must contain a browser-generated optimistic command parameter.")
                        (is (= (:operation rendered-complete-action)
                               (:operation command)))
                        (is (= (:arguments rendered-complete-action)
                               (:arguments command)))
                        (is (= (:observed-basis rendered-complete-action)
                               (:observed-basis command)))
                        (is (= (:scope rendered-complete-action)
                               (:scope command)))
                        (is (= (:fact-versions rendered-complete-action)
                               (:fact-versions command)))
                        (is (some? (:command-id command)))
                        (is (some? (:execution-id command)))))

                    (testing "the real server path commits Complete authoritatively"
                      (is (some?
                           (wait-for-authoritative-done!
                            system
                            request-id))
                          (pr-str @(:diagnostics browser-context)))
                      (is
                       (eventually
                        default-timeout-ms
                        #(some
                          (fn [{:keys [status]}]
                            (when (< status 400) status))
                          (drop
                           complete-response-start
                           (:complete-responses
                            @(:diagnostics browser-context)))))
                       (pr-str @(:diagnostics browser-context))))

                    (testing "Complete settlement performs a post-commit progression-bearing authoritative Request-list reread"
                      (is
                       (eventually
                        default-timeout-ms
                        #(progression-bearing-request-list-refresh
                          (:diagnostics browser-context)
                          complete-fragment-request-start))
                       (pr-str @(:diagnostics browser-context)))
                      (is
                       (eventually
                        default-timeout-ms
                        #(successful-request-list-response-after?
                          (:diagnostics browser-context)
                          complete-fragment-response-start))
                       (pr-str @(:diagnostics browser-context))))

                    (testing "canonical Complete reread hides the terminal Request only after authority advances"
                      (let [refresh-request
                            (progression-bearing-request-list-refresh
                             (:diagnostics browser-context)
                             complete-fragment-request-start)

                            required-basis
                            (some-> refresh-request
                                    :progression
                                    xtdb-live/strongest-required-basis)]
                        (is (some? required-basis)
                            (pr-str refresh-request))
                        (is (and
                             (some? pre-complete-basis)
                             (some? required-basis)
                             (xtdb-live/basis-advances?
                              pre-complete-basis
                              required-basis))
                            "The authoritative Complete reread minimum must strictly advance the rendered on-the-way basis.")
                        (is (true?
                             (wait-for-request-card-absent!
                              page
                              request-id))
                            "The default board hides terminal Requests only after authoritative canonical replacement; optimism itself cannot remove the card.")))

                    (testing "reload reconstructs terminal completion from persisted authority"
                      (.reload page)
                      (is (true?
                           (wait-for-request-card-absent!
                            page
                            request-id)))
                      (is (= :done
                             (request/status
                              (request/require-request system request-id)))))))

                (let [cancel-button
                      (.locator page (cancel-button-selector cancel-request-id))

                      rendered-cancel-action
                      (decode-rendered-action cancel-button)

                      pre-cancel-basis
                      (:observed-basis rendered-cancel-action)

                      cancel-request-start
                      (count
                       (:cancel-requests
                        @(:diagnostics browser-context)))

                      cancel-response-start
                      (count
                       (:cancel-responses
                        @(:diagnostics browser-context)))

                      cancel-fragment-request-start
                      (count
                       (:request-list-fragment-requests
                        @(:diagnostics browser-context)))

                      cancel-fragment-response-start
                      (count
                       (:request-list-fragment-responses
                        @(:diagnostics browser-context)))]
                  (testing "a helper-owned open Request exposes owner Cancel without browser-owned correlation identity"
                    (is (= 1 (.count cancel-button))
                        (pr-str @(:diagnostics browser-context)))
                    (is (= :open
                           (request/status
                            (request/require-request system cancel-request-id))))
                    (is (= request.choreo/cancel-operation
                           (:operation rendered-cancel-action)))
                    (is (= {:request-id cancel-request-id}
                           (:arguments rendered-cancel-action)))
                    (is (some? pre-cancel-basis))
                    (is (not (contains? rendered-cancel-action :command-id)))
                    (is (not (contains? rendered-cancel-action :execution-id))))

                  (cancel-through-browser! page cancel-request-id)

                  (testing "the browser independently creates the protocol-v3 Cancel command"
                    (is
                     (eventually
                      default-timeout-ms
                      #(when (> (count (:cancel-requests
                                       @(:diagnostics browser-context)))
                                cancel-request-start)
                         (last (:cancel-requests
                                @(:diagnostics browser-context)))))
                     (pr-str @(:diagnostics browser-context)))

                    (let [cancel-request-wire
                          (last (:cancel-requests
                                 @(:diagnostics browser-context)))

                          params
                          (encoded-form-params (:post-data cancel-request-wire))

                          encoded-command
                          (get params example.app/optimistic-command-param)

                          command
                          (some-> encoded-command
                                  edn/read-string
                                  optimistic.protocol/wire->command)]
                      (is (string? encoded-command)
                          "The real Cancel POST must contain a browser-generated optimistic command parameter.")
                      (is (= (:operation rendered-cancel-action)
                             (:operation command)))
                      (is (= (:arguments rendered-cancel-action)
                             (:arguments command)))
                      (is (= (:observed-basis rendered-cancel-action)
                             (:observed-basis command)))
                      (is (= (:scope rendered-cancel-action)
                             (:scope command)))
                      (is (= (:fact-versions rendered-cancel-action)
                             (:fact-versions command)))
                      (is (some? (:command-id command)))
                      (is (some? (:execution-id command)))))

                  (testing "the real server path commits Cancel authoritatively"
                    (is (some?
                         (wait-for-authoritative-cancelled!
                          system
                          cancel-request-id))
                        (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(some
                        (fn [{:keys [status]}]
                          (when (< status 400) status))
                        (drop
                         cancel-response-start
                         (:cancel-responses
                          @(:diagnostics browser-context)))))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "Cancel settlement performs a post-commit progression-bearing authoritative Request-list reread"
                    (is
                     (eventually
                      default-timeout-ms
                      #(progression-bearing-request-list-refresh
                        (:diagnostics browser-context)
                        cancel-fragment-request-start))
                     (pr-str @(:diagnostics browser-context)))
                    (is
                     (eventually
                      default-timeout-ms
                      #(successful-request-list-response-after?
                        (:diagnostics browser-context)
                        cancel-fragment-response-start))
                     (pr-str @(:diagnostics browser-context))))

                  (testing "canonical Cancel reread hides the terminal Request only after authority advances"
                    (let [refresh-request
                          (progression-bearing-request-list-refresh
                           (:diagnostics browser-context)
                           cancel-fragment-request-start)

                          required-basis
                          (some-> refresh-request
                                  :progression
                                  xtdb-live/strongest-required-basis)]
                      (is (some? required-basis)
                          (pr-str refresh-request))
                      (is (and
                           (some? pre-cancel-basis)
                           (some? required-basis)
                           (xtdb-live/basis-advances?
                            pre-cancel-basis
                            required-basis))
                          "The authoritative Cancel reread minimum must strictly advance the rendered open basis.")
                      (is (true?
                           (wait-for-request-card-absent!
                            page
                            cancel-request-id))
                          "The default board hides cancelled Requests only after authoritative canonical replacement; optimism itself cannot remove the card.")))

                  (testing "reload reconstructs terminal cancellation from persisted authority"
                    (.reload page)
                    (is (true?
                         (wait-for-request-card-absent!
                          page
                          cancel-request-id)))
                    (is (= :cancelled
                           (request/status
                            (request/require-request system cancel-request-id))))))


                (let [reassign-claim-button
                      (.locator page (claim-button-selector reassign-request-id))

                      reassign-claim-fragment-request-start
                      (count
                       (:request-list-fragment-requests
                        @(:diagnostics browser-context)))]

                  (testing "the independent Reassign Request is first claimed through the real browser"
                    (is (= 1 (.count reassign-claim-button))
                        (pr-str @(:diagnostics browser-context)))
                    (is (= :open
                           (request/status
                            (request/require-request system reassign-request-id)))))

                  (claim-through-browser! page reassign-request-id)

                  (is (some?
                       (wait-for-authoritative-claim!
                        system
                        reassign-request-id))
                      (pr-str @(:diagnostics browser-context)))

                  (is
                   (eventually
                    default-timeout-ms
                    #(progression-bearing-request-list-refresh
                      (:diagnostics browser-context)
                      reassign-claim-fragment-request-start))
                   (pr-str @(:diagnostics browser-context)))

                  (let [target-button
                        (.locator
                         page
                         (reassign-target-selector
                          reassign-request-id
                          target-helper-id))

                        reassign-trigger
                        (.locator
                         page
                         (reassign-trigger-selector reassign-request-id))]

                    (testing "the canonical claimed card exposes the real v689 target-helper menu"
                      (is
                       (eventually
                        default-timeout-ms
                        #(when (= 1 (.count reassign-trigger)) reassign-trigger))
                       (pr-str @(:diagnostics browser-context)))
                      (is (= 0
                             (.count
                              (.locator
                               page
                               (str
                                "#humanhelp-request-" reassign-request-id
                                " [name=\"helper-id\"]"))))
                          "Reassign target identity must come from a preclosed semantic action, not mutable form input.")

                      (when-not (.isVisible reassign-trigger)
                        (.click
                         (.locator
                          page
                          (request-summary-selector reassign-request-id))))

                      (.click reassign-trigger)
                      (.waitFor target-button)

                      (let [rendered-reassign-action
                            (decode-rendered-action target-button)

                            pre-reassign-basis
                            (:observed-basis rendered-reassign-action)

                            reassign-request-start
                            (count
                             (:reassign-requests
                              @(:diagnostics browser-context)))

                            reassign-response-start
                            (count
                             (:reassign-responses
                              @(:diagnostics browser-context)))

                            fragment-request-start
                            (count
                             (:request-list-fragment-requests
                              @(:diagnostics browser-context)))

                            fragment-response-start
                            (count
                             (:request-list-fragment-responses
                              @(:diagnostics browser-context)))]

                        (is (= request.choreo/reassign-operation
                               (:operation rendered-reassign-action)))
                        (is (= {:request-id reassign-request-id
                                :helper-id target-helper-id}
                               (:arguments rendered-reassign-action)))
                        (is (some? pre-reassign-basis))
                        (is (not (contains? rendered-reassign-action :command-id)))
                        (is (not (contains? rendered-reassign-action :execution-id)))
                        (is (= helper-id
                               (authoritative-primary-helper-id
                                system
                                reassign-request-id)))

                        ;; Close/reopen through the actual trigger helper so the
                        ;; action is activated through the same interaction a
                        ;; user performs, rather than Playwright force-clicking
                        ;; a hidden semantic control.
                        (.click reassign-trigger)
                        (reassign-through-browser!
                         page
                         reassign-request-id
                         target-helper-id)

                        (testing "the browser generates Reassign protocol-v3 identity from the selected preclosed target action"
                          (is
                           (eventually
                            default-timeout-ms
                            #(when (> (count (:reassign-requests
                                             @(:diagnostics browser-context)))
                                      reassign-request-start)
                               (last
                                (:reassign-requests
                                 @(:diagnostics browser-context)))))
                           (pr-str @(:diagnostics browser-context)))

                          (let [wire-request
                                (last
                                 (:reassign-requests
                                  @(:diagnostics browser-context)))

                                params
                                (encoded-form-params (:post-data wire-request))

                                encoded-command
                                (get params example.app/optimistic-command-param)

                                command
                                (some-> encoded-command
                                        edn/read-string
                                        optimistic.protocol/wire->command)]
                            (is (string? encoded-command))
                            (is (= (:operation rendered-reassign-action)
                                   (:operation command)))
                            (is (= (:arguments rendered-reassign-action)
                                   (:arguments command)))
                            (is (= (:observed-basis rendered-reassign-action)
                                   (:observed-basis command)))
                            (is (= (:scope rendered-reassign-action)
                                   (:scope command)))
                            (is (= (:fact-versions rendered-reassign-action)
                                   (:fact-versions command)))
                            (is (some? (:command-id command)))
                            (is (some? (:execution-id command)))))

                        (testing "the production Request model authoritatively replaces the primary helper"
                          (is (= target-helper-id
                                 (wait-for-authoritative-primary-helper!
                                  system
                                  reassign-request-id))
                              (pr-str @(:diagnostics browser-context)))
                          (is (= :claimed
                                 (request/status
                                  (request/require-request
                                   system
                                   reassign-request-id))))
                          (is
                           (eventually
                            default-timeout-ms
                            #(some
                              (fn [{:keys [status]}]
                                (when (< status 400) status))
                              (drop
                               reassign-response-start
                               (:reassign-responses
                                @(:diagnostics browser-context)))))
                           (pr-str @(:diagnostics browser-context))))

                        (testing "Reassign settlement performs progression-bearing authoritative reacquisition"
                          (is
                           (eventually
                            default-timeout-ms
                            #(progression-bearing-request-list-refresh
                              (:diagnostics browser-context)
                              fragment-request-start))
                           (pr-str @(:diagnostics browser-context)))
                          (is
                           (eventually
                            default-timeout-ms
                            #(successful-request-list-response-after?
                              (:diagnostics browser-context)
                              fragment-response-start))
                           (pr-str @(:diagnostics browser-context))))

                        (testing "canonical Reassign reread advances authority and reverses the available target"
                          (let [refresh-request
                                (progression-bearing-request-list-refresh
                                 (:diagnostics browser-context)
                                 fragment-request-start)

                                required-basis
                                (some-> refresh-request
                                        :progression
                                        xtdb-live/strongest-required-basis)

                                former-helper-target
                                (.locator
                                 page
                                 (reassign-target-selector
                                  reassign-request-id
                                  helper-id))

                                current-primary-target
                                (.locator
                                 page
                                 (reassign-target-selector
                                  reassign-request-id
                                  target-helper-id))]
                            (is (some? required-basis)
                                (pr-str refresh-request))
                            (is (and
                                 (some? pre-reassign-basis)
                                 (some? required-basis)
                                 (xtdb-live/basis-advances?
                                  pre-reassign-basis
                                  required-basis))
                                "The authoritative Reassign reread minimum must strictly advance the rendered claimed basis.")
                            (is
                             (eventually
                              default-timeout-ms
                              #(when (= 1 (.count former-helper-target))
                                 former-helper-target))
                             "After canonical reassignment, the former helper becomes the legitimate alternative target.")
                            (is (= 0 (.count current-primary-target))
                                "The canonical Reassign menu must exclude the helper who is now primary.")))

                        (testing "reload reconstructs the reassigned primary helper from persisted authority"
                          (.reload page)
                          (is (= target-helper-id
                                 (authoritative-primary-helper-id
                                  system
                                  reassign-request-id)))
                          (is (= :claimed
                                 (request/status
                                  (request/require-request
                                   system
                                   reassign-request-id))))
                          (let [trigger-after-reload
                                (.locator
                                 page
                                 (reassign-trigger-selector
                                  reassign-request-id))

                                former-helper-target-after-reload
                                (.locator
                                 page
                                 (reassign-target-selector
                                  reassign-request-id
                                  helper-id))

                                current-primary-target-after-reload
                                (.locator
                                 page
                                 (reassign-target-selector
                                  reassign-request-id
                                  target-helper-id))]
                            (is
                             (eventually
                              default-timeout-ms
                              #(when (= 1 (.count trigger-after-reload))
                                 trigger-after-reload)))
                            (.click trigger-after-reload)
                            (is (= 1
                                   (.count
                                    former-helper-target-after-reload)))
                            (is (= 0
                                   (.count
                                    current-primary-target-after-reload)))))))))

                (testing "no browser/page/network failure is hidden behind the green lifecycle"
                  (is (clean-browser-diagnostics?
                       @(:diagnostics browser-context))
                      (pr-str @(:diagnostics browser-context))))))))
          (finally
            (close-browser-context! browser-context)
            (stop-browser! browser))))
      (finally
        (stop-runtime! runtime)))))

;; =============================================================================
;; Explicit browser gate
;; =============================================================================

(defn -main
  [& _args]
  (let [{:keys [fail error] :as result}
        (run-tests 'net.humanhelp.example.chromium-acceptance)]
    (if (zero? (+ fail error))
      (do
        (println "HumanHelp Chromium acceptance: PASS")
        result)
      (do
        (println "HumanHelp Chromium acceptance: FAIL")
        (System/exit 1)))))
