(ns net.humanhelp.example.chromium-acceptance
  "Real Chromium acceptance for the production-model-backed HumanHelp example app.

   This namespace is intentionally *not* named ...-test. Ordinary JVM tests must
   remain independent of Chromium and of the generated browser artifact. The
   browser gate invokes -main explicitly after building the exact HumanHelp
   gesso-live.js artifact.

   The first scenario is Request Claim and deliberately crosses the real joins
   that the preflight recovery work is meant to protect:

     real HumanHelp Ring middleware / session
       -> real /app render
       -> generated HumanHelp Gesso browser artifact
       -> real HTMX request construction
       -> browser-generated protocol-v3 command
       -> real Claim route
       -> production Request Choreo/model commit
       -> settlement + authoritative reacquisition
       -> real DOM
       -> reload from persisted authority

   The test seeds only authoritative prerequisite data (Users, helper authority,
   and one open production Request). It never constructs, injects, or edits
   __gesso_live_optimistic_command. The command observed on the Claim POST must
   have been generated by the browser runtime itself."
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.string :as str]
   [clojure.test :refer [deftest is run-tests testing]]
   [com.biffweb.core :as biff.core]
   [gesso.live.application-preflight :as application-preflight]
   [gesso.live.optimistic.protocol :as optimistic.protocol]
   [gesso.model.command :as model.command]
   [gesso.model.tx :as model.tx]
   [net.humanhelp :as humanhelp]
   [net.humanhelp.components.phone-auth.sms :as phone-auth.sms]
   [net.humanhelp.example.app :as example.app]
   [net.humanhelp.example.routes :as routes]
   [net.humanhelp.site.mock-data :as mock-data]
   [net.humanhelp.site.model.membership.domain :as membership.domain]
   [net.humanhelp.site.model.organization.core :as organization]
   [net.humanhelp.site.model.request.choreo :as request.choreo]
   [net.humanhelp.site.model.request.core :as request]
   [net.humanhelp.site.model.user.domain :as user.domain]
   [ring.middleware.session.memory :as session.memory]
   [xtdb.node :as xtn])
  (:import
   (com.microsoft.playwright
    Browser
    BrowserContext
    BrowserType$LaunchOptions
    ConsoleMessage
    Page
    Playwright
    Playwright$CreateOptions
    Request
    Response
    Route
    Route$FulfillOptions
    WebError)
   (java.io File)
   (java.net ServerSocket URI URLDecoder)
   (java.nio.charset StandardCharsets)
   (java.time Instant)
   (java.util UUID)
   (java.util.function Consumer)))

;; =============================================================================
;; Stable scenario values
;; =============================================================================

(def ^:private helper-id
  (UUID/fromString "a1000000-0000-0000-0000-000000000679"))

(def ^:private requestor-id
  (UUID/fromString "a2000000-0000-0000-0000-000000000679"))

(def ^:private helper-membership-id
  (UUID/fromString "a3000000-0000-0000-0000-000000000679"))

(def ^:private helper-role-assignment-id
  (UUID/fromString "a4000000-0000-0000-0000-000000000679"))

(def ^:private helper-phone
  "2065550679")

(def ^:private helper-e164
  "+12065550679")

(def ^:private auth-code
  "679679")

(def ^:private fixture-time
  (Instant/parse "2026-09-11T12:00:00Z"))

(def ^:private request-title
  "HumanHelp real Chromium Claim acceptance")

(def ^:private request-details
  "This Request exists only to prove the real rendered Claim trajectory.")

(def ^:private request-location-detail
  "Chromium acceptance fixture")

(def ^:private default-timeout-ms
  15000)

(def ^:private chromium-candidates
  ["chromium"
   "chromium-browser"
   "google-chrome"
   "google-chrome-stable"])

(def ^:private htmx-resource-candidates
  ["META-INF/resources/webjars/htmx.org/2.0.7/dist/htmx.min.js"
   "META-INF/resources/webjars/htmx.org/2.0.7/dist/htmx.js"])

(def ^:private sse-resource-candidates
  ["META-INF/resources/webjars/htmx-ext-sse/2.2.4/dist/sse.min.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/dist/sse.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/sse.min.js"
   "META-INF/resources/webjars/htmx-ext-sse/2.2.4/sse.js"])

(def ^:private htmx-url
  "https://unpkg.com/htmx.org@2.0.7")

(def ^:private sse-url
  "https://cdn.jsdelivr.net/npm/htmx-ext-sse@2.2.4")

;; =============================================================================
;; Errors / small helpers
;; =============================================================================

(defn- acceptance-error
  ([kind message]
   (acceptance-error kind message {}))
  ([kind message data]
   (ex-info
    message
    (merge
     {:error/type :net.humanhelp.example.chromium-acceptance/error
      :error/kind kind}
     data))))

(defn- consumer
  [f]
  (reify Consumer
    (accept [_ value]
      (f value))))

(defn- path-directories
  []
  (let [value (or (System/getenv "PATH") "")
        separator
        (re-pattern
         (java.util.regex.Pattern/quote File/pathSeparator))]
    (if (str/blank? value)
      []
      (str/split value separator -1))))

(defn- executable-path
  [value]
  (let [file (io/file (str value))]
    (when (and (.isFile ^File file)
               (.canExecute ^File file))
      (.toAbsolutePath (.toPath ^File file)))))

(defn- command-path
  [command]
  (some
   (fn [directory]
     (executable-path
      (io/file
       (if (str/blank? directory) "." directory)
       command)))
   (path-directories)))

(defn- chromium-executable
  []
  (let [override
        (or
         (some-> (System/getenv "HUMANHELP_CHROMIUM") str/trim not-empty)
         (some-> (System/getenv "GESSO_CHROMIUM") str/trim not-empty))]
    (if override
      (or
       (executable-path override)
       (command-path override)
       (throw
        (acceptance-error
         :invalid-chromium-override
         "Configured Chromium executable is unavailable."
         {:override override})))
      (or
       (some command-path chromium-candidates)
       (throw
        (acceptance-error
         :chromium-not-found
         "HumanHelp Chromium acceptance requires system Chromium/Chrome or HUMANHELP_CHROMIUM."
         {:checked chromium-candidates}))))))

(defn- available-port
  []
  (with-open [socket (ServerSocket. 0)]
    (.getLocalPort socket)))

(defn- uri-path
  [url]
  (.getPath (URI/create url)))

(defn- decode-form-component
  [value]
  (URLDecoder/decode
   (str (or value ""))
   (.name StandardCharsets/UTF_8)))

(defn- encoded-form-params
  [post-data]
  (into
   {}
   (map
    (fn [pair]
      (let [[k v]
            (str/split pair #"=" 2)]
        [(decode-form-component k)
         (decode-form-component v)])))
   (remove str/blank?
           (str/split (or post-data "") #"&"))))

(defn- eventually
  ([pred]
   (eventually 10000 pred))
  ([timeout-ms pred]
   (let [deadline (+ (System/currentTimeMillis) timeout-ms)]
     (loop []
       (let [value
             (try
               (pred)
               (catch Throwable _
                 nil))]
         (cond
           value
           value

           (< (System/currentTimeMillis) deadline)
           (do
             (Thread/sleep 25)
             (recur))

           :else
           nil))))))

;; =============================================================================
;; Deterministic authoritative fixture
;; =============================================================================

(defn- user-command
  [{:keys [id phone email display-name]}]
  (user.domain/create-user-command
   (cond->
    {:id id
     :display-name display-name
     :now fixture-time}
     phone
     (assoc
      :phone phone
      :phone-verified? true)

     email
     (assoc
      :email email
      :email-verified? true))))

(defn- seed-users!
  [ctx]
  (model.tx/transact!
   ctx
   {:commands
    [(user-command
      {:id helper-id
       :phone helper-e164
       :display-name "Chromium Helper"})

     (user-command
      {:id requestor-id
       :email "chromium-requestor@example.com"
       :display-name "Chromium Requestor"})]

    :emit false}))

(defn- seed-helper-authority!
  [ctx]
  (let [membership-command
        (membership.domain/create-membership-command
         {:id helper-membership-id
          :user-id helper-id
          :organization-id mock-data/organization-id
          :now fixture-time})

        membership-document
        (model.command/after membership-command)

        role-command
        (membership.domain/create-role-assignment-command
         membership-document
         {:id helper-role-assignment-id
          :role :helper
          :scope
          (organization/location-scope
           mock-data/default-location-id)
          :now fixture-time})]
    (model.tx/transact!
     ctx
     {:commands [membership-command role-command]
      :emit false})))

(defn- create-open-request!
  [ctx]
  (request/create
   (assoc
    ctx
    :current-user/id requestor-id
    :biff.fx/now fixture-time
    :biff.fx/seed 679)
   {:organization-id mock-data/organization-id
    :location-id mock-data/default-location-id
    :content
    {:title request-title
     :details request-details
     :location-detail request-location-detail}}))

(defn- seed-scenario!
  [system]
  (let [seed-ctx
        (assoc
         system
         :biff.fx/now fixture-time
         :biff.fx/seed 679)

        users-transaction
        (seed-users! seed-ctx)

        users-ctx
        (:ctx users-transaction)

        fixture-result
        (mock-data/ensure! users-ctx)

        fixture-ctx
        (:ctx fixture-result)

        helper-transaction
        (seed-helper-authority! fixture-ctx)

        helper-ctx
        (:ctx helper-transaction)

        create-result
        (create-open-request! helper-ctx)]
    {:ctx helper-ctx
     :request (:request create-result)
     :create-result create-result}))

;; =============================================================================
;; Actual HumanHelp runtime
;; =============================================================================

(defn- start-runtime!
  []
  (let [port
        (available-port)

        base-url
        (str "http://127.0.0.1:" port)

        node
        (xtn/start-node {})]
    (try
      (let [application-assembly
            (humanhelp/require-application-assembly!)

            initial-system
            (merge
             humanhelp/initial-system
             {:biff.xtdb/node node
              :biff.ring/host "127.0.0.1"
              :biff.ring/port port
              :biff.ring/base-url base-url
              :biff.ring/secure false
              :biff.ring/ssl-redirect false
              :biff.ring/fallback-session-store
              (session.memory/memory-store)
              :biff.core/stop
              [(fn []
                 (.close node))]})

            system
            (application-preflight/start-biff-application!
             application-assembly
             initial-system
             #'humanhelp/modules
             [humanhelp/use-gesso-live
              humanhelp/use-aleph])]
        {:system system
         :base-url base-url})
      (catch Throwable error
        (try
          (.close node)
          (catch Throwable _))
        (throw error)))))

(defn- stop-runtime!
  [{:keys [system]}]
  (when system
    (biff.core/stop system))
  nil)

;; =============================================================================
;; Browser control / diagnostics
;; =============================================================================

(defn- start-browser!
  []
  (let [chromium-path
        (chromium-executable)

        create-options
        (doto (Playwright$CreateOptions.)
          (.setEnv
           (assoc
            (into {} (System/getenv))
            "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD"
            "1")))

        playwright
        (Playwright/create create-options)]
    (try
      (let [launch-options
            (doto (BrowserType$LaunchOptions.)
              (.setExecutablePath chromium-path)
              (.setHeadless true)
              (.setTimeout 20000.0))

            browser
            (.launch (.chromium playwright) launch-options)]
        {:playwright playwright
         :browser browser
         :chromium-executable chromium-path})
      (catch Throwable error
        (.close playwright)
        (throw error)))))

(defn- stop-browser!
  [{:keys [^Browser browser ^Playwright playwright]}]
  (when browser
    (.close browser))
  (when playwright
    (.close playwright))
  nil)

(defn- resource-text
  [candidates]
  (some-> (some io/resource candidates)
          slurp))

(defn- fulfill!
  [^Route route content-type body]
  (.fulfill
   route
   (doto (Route$FulfillOptions.)
     (.setStatus 200)
     (.setContentType content-type)
     (.setBody body))))

(defn- install-local-browser-assets!
  "Use pinned local HTMX/SSE bytes when the browser-test classpath supplies
   them (for example in Gesso's development/test environment). When unavailable,
   leave the application's real CDN request untouched instead of silently
   substituting a different implementation."
  [^BrowserContext context]
  (when-let [htmx (resource-text htmx-resource-candidates)]
    (.route
     context
     htmx-url
     (consumer
      #(fulfill! % "text/javascript; charset=utf-8" htmx))))

  (when-let [sse (resource-text sse-resource-candidates)]
    (.route
     context
     sse-url
     (consumer
      #(fulfill! % "text/javascript; charset=utf-8" sse))))

  ;; These assets are presentation/optional behavior outside the Claim protocol
  ;; being accepted here. Keep the real URLs in application markup, but make the
  ;; headless test independent of unrelated CDN availability.
  (.route
   context
   "https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/basecoat.cdn.min.css"
   (consumer #(fulfill! % "text/css; charset=utf-8" "")))

  (.route
   context
   "https://cdn.jsdelivr.net/npm/basecoat-css@0.3.11/dist/js/all.min.js"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://unpkg.com/htmx-ext-ws@2.0.2/ws.js"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://unpkg.com/hyperscript.org@0.9.14"
   (consumer #(fulfill! % "text/javascript; charset=utf-8" "")))

  (.route
   context
   "https://fonts.googleapis.com/**"
   (consumer #(fulfill! % "text/css; charset=utf-8" "")))

  context)

(defn- new-browser-context!
  [{:keys [^Browser browser]}]
  (let [context
        (.newContext browser)

        diagnostics
        (atom
         {:console-errors []
          :web-errors []
          :request-failures []
          :claim-requests []
          :claim-responses []})]

    (.setDefaultTimeout context (double default-timeout-ms))
    (.setDefaultNavigationTimeout context (double default-timeout-ms))

    (.onConsoleMessage
     context
     (consumer
      (fn [^ConsoleMessage message]
        (when (#{"error" "assert"} (.type message))
          (swap!
           diagnostics
           update
           :console-errors
           conj
           {:type (.type message)
            :text (.text message)})))))

    (.onWebError
     context
     (consumer
      (fn [^WebError error]
        (swap!
         diagnostics
         update
         :web-errors
         conj
         {:error (.error error)}))))

    (.onRequestFailed
     context
     (consumer
      (fn [^Request request]
        (swap!
         diagnostics
         update
         :request-failures
         conj
         {:method (.method request)
          :url (.url request)
          :failure (.failure request)}))))

    (.onRequest
     context
     (consumer
      (fn [^Request request]
        (when (and
               (= "POST" (.method request))
               (str/ends-with? (uri-path (.url request)) "/claim"))
          (swap!
           diagnostics
           update
           :claim-requests
           conj
           {:url (.url request)
            :post-data (.postData request)})))))

    (.onResponse
     context
     (consumer
      (fn [^Response response]
        (when (and
               (= "POST" (.method (.request response)))
               (str/ends-with? (uri-path (.url response)) "/claim"))
          (swap!
           diagnostics
           update
           :claim-responses
           conj
           {:url (.url response)
            :status (.status response)})))))

    (install-local-browser-assets! context)

    {:context context
     :diagnostics diagnostics}))

(defn- close-browser-context!
  [{:keys [^BrowserContext context]}]
  (when context
    (.close context))
  nil)

(defn- clean-browser-diagnostics?
  [{:keys [console-errors web-errors request-failures]}]
  (and
   (empty? console-errors)
   (empty? web-errors)
   (empty? request-failures)))

;; =============================================================================
;; Actual browser actions
;; =============================================================================

(def ^:private generate-code-var
  (ns-resolve
   'net.humanhelp.components.phone-auth.sms
   'generate-code))

(defn- sign-in!
  [^Page page base-url]
  (.navigate page (str base-url "/"))

  (let [phone-input
        (.locator page "#phone-display")]
    (.waitFor phone-input)
    (.fill phone-input helper-phone)
    (.click
     (.locator
      page
      "#phone-auth-send-form button[type=\"submit\"]")))

  (let [code-input
        (.locator page "#code")]
    (.waitFor code-input)
    (.fill code-input auth-code)
    (.click
     (.locator
      page
      "#phone-auth-verify-form button[type=\"submit\"]")))

  (.waitForURL
   page
   (reify java.util.function.Predicate
     (test [_ url]
       (= "/app" (uri-path url)))))

  page)

(defn- claim-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"claim\"]"))

(defn- request-summary-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-summary]"))

(defn- unclaim-button-selector
  [request-id]
  (str
   "#humanhelp-request-" request-id
   " [data-humanhelp-request-operation=\"unclaim\"]"))

(defn- claim-through-browser!
  [^Page page request-id]
  (let [claim-button
        (.locator page (claim-button-selector request-id))]
    (.waitFor claim-button)

    (when-not (.isVisible claim-button)
      (.click
       (.locator page (request-summary-selector request-id))))

    (.click claim-button))

  request-id)

(defn- wait-for-authoritative-claim!
  [system request-id]
  (eventually
   default-timeout-ms
   (fn []
     (let [request-document
           (request/request system request-id)]
       (when (= :claimed (some-> request-document request/status))
         request-document)))))

(defn- wait-for-claimed-dom!
  [^Page page request-id]
  (let [unclaim-button
        (.locator page (unclaim-button-selector request-id))]
    (.waitFor unclaim-button)
    unclaim-button))

;; =============================================================================
;; Claim acceptance
;; =============================================================================

(deftest real-rendered-claim-crosses-browser-runtime-and-persists-test
  (let [runtime
        (start-runtime!)]
    (try
      (let [{:keys [system base-url]}
            runtime

            {:keys [request]}
            (seed-scenario! system)

            request-id
            (request/request-id request)

            browser
            (start-browser!)

            browser-context
            (new-browser-context! browser)]
        (try
          (let [^BrowserContext context
                (:context browser-context)

                ^Page page
                (.newPage context)]
            (with-redefs-fn
              {generate-code-var
               (fn [_length]
                 auth-code)}
              (fn []
                (sign-in! page base-url)

                (testing "the authoritative initial /app render exposes a real semantic Claim control"
                  (is (= 1
                         (.count
                          (.locator
                           page
                           (claim-button-selector request-id)))))
                  (is (= :open
                         (request/status
                          (request/require-request system request-id)))))

                (claim-through-browser! page request-id)

                (testing "the browser, not the test, produces protocol-v3 command transport"
                  (is
                   (eventually
                    default-timeout-ms
                    #(first (:claim-requests @(:diagnostics browser-context))))
                   (pr-str @(:diagnostics browser-context)))

                  (let [claim-request
                        (first (:claim-requests @(:diagnostics browser-context)))

                        params
                        (encoded-form-params (:post-data claim-request))

                        encoded-command
                        (get params example.app/optimistic-command-param)

                        command
                        (some-> encoded-command
                                edn/read-string
                                optimistic.protocol/wire->command)]
                    (is (string? encoded-command)
                        "The real HTMX POST must contain the browser-generated optimistic command parameter.")
                    (is (= request.choreo/claim-operation
                           (:operation command)))
                    (is (= {:request-id request-id}
                           (:arguments command)))
                    (is (some? (:command-id command)))
                    (is (some? (:execution-id command)))
                    (is (some? (:observed-basis command)))))

                (testing "the real server path commits Claim authoritatively"
                  (is (some?
                       (wait-for-authoritative-claim!
                        system
                        request-id))
                      (pr-str @(:diagnostics browser-context)))
                  (is
                   (eventually
                    default-timeout-ms
                    #(some
                      (fn [{:keys [status]}]
                        (when (< status 400) status))
                      (:claim-responses @(:diagnostics browser-context))))
                   (pr-str @(:diagnostics browser-context))))

                (testing "settlement/reacquisition replaces the visible affordance with authoritative claimed state"
                  (is (some?
                       (wait-for-claimed-dom! page request-id))
                      (pr-str @(:diagnostics browser-context))))

                (testing "reload reconstructs the claimed state from authority rather than provisional DOM"
                  (.reload page)
                  (is (some?
                       (wait-for-claimed-dom! page request-id)))
                  (is (= :claimed
                         (request/status
                          (request/require-request system request-id)))))

                (testing "no browser/page/network failure is hidden behind the green lifecycle"
                  (is (clean-browser-diagnostics?
                       @(:diagnostics browser-context))
                      (pr-str @(:diagnostics browser-context)))))))
          (finally
            (close-browser-context! browser-context)
            (stop-browser! browser))))
      (finally
        (stop-runtime! runtime)))))

;; =============================================================================
;; Explicit browser gate
;; =============================================================================

(defn -main
  [& _args]
  (let [{:keys [fail error] :as result}
        (run-tests 'net.humanhelp.example.chromium-acceptance)]
    (if (zero? (+ fail error))
      (do
        (println "HumanHelp Chromium acceptance: PASS")
        result)
      (do
        (println "HumanHelp Chromium acceptance: FAIL")
        (System/exit 1)))))
